<?php
/**
 * @package      UserPictures
 * @version      $Id$
 * @author       Florian Schießl
 * @link         http://www.ifs-net.de
 * @copyright    Copyright (C) 2008
 * @license      http://www.gnu.org/copyleft/gpl.html GNU General Public License
 */

/**
 * initialise block
 * 
 * @author       The PostNuke Development Team
 */
function UserPictures_latestsmallblock_init()
{
    // Security
    pnSecAddSchema('UserPictures:latestsmallblock:', 'Block title::');
}

/**
 * get information on block
 * 
 * @author       The PostNuke Development Team
 * @return       array       The block information
 */
function UserPictures_latestsmallblock_info()
{
    return array('text_type'      => 'latestsmall',
                 'module'         => 'UserPictures',
                 'text_type_long' => 'Show latest UserPictures items (more compact)',
                 'allow_multiple' => true,
                 'form_content'   => false,
                 'form_refresh'   => false,
                 'show_preview'   => true);
}

/**
 * display block
 * 
 * @author       The PostNuke Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the rendered bock
 */
function UserPictures_latestsmallblock_display($blockinfo)
{
    if (!SecurityUtil::checkPermission('UserPictures:latestsmallblock', "$blockinfo[title]::", ACCESS_READ)) return false;

    // Get variables from content block
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['numrows'])) {
        $vars['numrows'] = 2;
    }
    // Defaults
    if (empty($vars['numcols'])) {
        $vars['numcols'] = 3;
    }
    
    // Check if the UserPictures module is available. 
    if (!pnModAvailable('UserPictures')) return false;

	// Add stylesheet    
	PageUtil::AddVar('stylesheet', ThemeUtil::getModuleStylesheet('UserPictures'));
	pnModLangLoad('UserPictures','user');

    // Populate block info and pass to theme
    $blockinfo['content'] = pnModAPIFunc('UserPictures','user','latest',array(
			'numcols' 	=> $vars['numrows'], 
			'nopager' 	=> 1,
			'small'		=> 1,
			'numrows' 	=> $vars['numcols']));
    return themesideblock($blockinfo);
}


/**
 * modify block settings
 * 
 * @author       The PostNuke Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function UserPictures_latestsmallblock_modify($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['numrows'])) {
        $vars['numrows'] = 2;
    }
    // Defaults
    if (empty($vars['numcols'])) {
        $vars['numcols'] = 5;
    }

    // Create output object
	$pnRender =& new pnRender('UserPictures');

	// As Admin output changes often, we do not want caching.
	$pnRender->caching = false;

    // assign the approriate values
	$pnRender->assign('numrows', $vars['numrows']);

    // assign the approriate values
	$pnRender->assign('numcols', $vars['numcols']);

    // Return the output that has been generated by this function
	return $pnRender->fetch('userpictures_block_latest_modify.htm');
}


/**
 * update block settings
 * 
 * @author       The PostNuke Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function UserPictures_latestsmallblock_update($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);
	
	// alter the corresponding variable
    $vars['numrows'] = FormUtil::getPassedValue('numrows');
	// alter the corresponding variable
    $vars['numcols'] = FormUtil::getPassedValue('numcols');
	
	// write back the new contents
    $blockinfo['content'] = pnBlockVarsToContent($vars);

	// clear the block cache
	$pnRender =& new pnRender('UserPictures');
	$pnRender->clear_cache('UserPictures_block_latest.htm');
	
    return $blockinfo;
}

?>